/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KP;

import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Derrick Abucheri
 */
public class PrintReceipt extends javax.swing.JFrame {
   // Connection conn =  null;
    //PreparedStatement pst = null;
    //Statement stm = null;
    //ResultSet rs = null;
    //String ItemSoldBy =  null;
    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
    }
    String lsubtot;
    String ltax;
    String lbonus;
    String lpayed;
    public PrintReceipt(String subtot,String tax,String bonus,String payed,TableModel tableModel) throws PrinterException) {
       initComponents();
        this.lsubtot=subtot;
        this.ltax=tax;
        this.lbonus=bonus;
        this.lpayed=payed;
        
        
       
         String alpha="1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ";  
         String s="";
          Random random=new Random();
          int randomLen=1+random.nextInt(10);
         for(int i=0;i<randomLen;i++){
         char ReceiptNo=alpha.charAt(random.nextInt(36));
         s+=ReceiptNo;
    }
   
    
     
        //txt_receipt.setText("          TIWI URBAN TRADERS LIMITED COMPANY");
         //txt_receipt.append("\n                TIWI SOKONI");
          //txt_receipt.append("\n                P.O BOX 98293-80100");
          // txt_receipt.append("\n                MOMBASA");
       txt_receipt.setText(txt_receipt.getText()+"         RECEIPT NUMBER:"+s+"\n");
          txt_receipt.setText(txt_receipt.getText()+""+"\n");
        txt_receipt.setText(txt_receipt.getText()+"               KENPHELIX PRODUCT              \n");
         txt_receipt.setText(txt_receipt.getText()+"                Sales Receipt                   \n");
        txt_receipt.setText(txt_receipt.getText()+"ITEM"+"     "+"QUANTITY"+"    "+"PRICE"+"        "+"TOTAL");
        txt_receipt.setText(txt_receipt.getText()+"\n");
         for(int i=0;i<tableModel.getRowCount();i++){
         String product=(String)tableModel.getValueAt(i, 0);
         String quantity=(String)tableModel.getValueAt(i, 1);
         int price=(int)tableModel.getValueAt(i, 2);
         int total=(int)tableModel.getValueAt(i, 3);
         txt_receipt.setText(txt_receipt.getText()+product+"          "+quantity+"          "+price+"         "+total);  
        txt_receipt.setText(txt_receipt.getText()+"\n");
         
        //txt_receipt.setText(txt_receipt.getText()+"\n");   
       /*txt_receipt.setText(txt_receipt.getText()+"    "+"SubTotal: "+ subtot + "\n");
        print.setText(print.getText()+"    "+"Payed: "+  payed+ "\n");
        print.setText(print.getText()+"    "+"Balance: " +balance + "\n");    
        print.setText(print.getText()+"******************\n");
        print.setText(print.getText()+"THANK YOU COME AGAIN........\n");*/
      
          }   
         
          txt_receipt.setText( txt_receipt.getText()+"\n");   
         txt_receipt.setText( txt_receipt.getText()+"Total Amount:"+ subtot + "\n");
         txt_receipt.setText( txt_receipt.getText()+"Amount Paid:"+  payed+ "\n");
         txt_receipt.setText( txt_receipt.getText()+"Tax Charged:" +tax + "\n");  
          txt_receipt.setText( txt_receipt.getText()+"Bonus Given:" +bonus + "\n"); 
        txt_receipt.setText(txt_receipt.getText()+"*****************************************\n");
        txt_receipt.setText(txt_receipt.getText()+"THANK YOU COME AGAIN........\n");
          txt_receipt.print();      
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_receipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/Print_24px.png"))); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_receipt.setEditable(false);
        txt_receipt.setColumns(20);
        txt_receipt.setRows(5);
        jScrollPane1.setViewportView(txt_receipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(406, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_receipt;
    // End of variables declaration//GEN-END:variables
}
